export const breeds = [
  {
    code: "affenpinscher",
    name: "Affenpinscher",
    image: 1,
    group: 1,
    origin: ["DE"],
    size: [1],
  },
  {
    code: "afghan_hound",
    name: "Afghan Hound",
    image: 2,
    group: 4,
    origin: ["AF"],
    size: [3],
  },
  {
    code: "airedale_terrier",
    name: "Airedale Terrier",
    image: 4,
    group: 2,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "akita",
    name: "Akita",
    image: 11,
    group: 6,
    origin: ["JP"],
    size: [3],
    variants: [
      {
        key: "japanese",
        label: "Japanese",
        group: 6,
        origin: ["JP"],
        size: [3],
      },
    ],
  },
  {
    code: "alaskan_malamute",
    name: "Alaskan Malamute",
    image: 14,
    group: 6,
    origin: ["US"],
    size: [2],
  },
  {
    code: "american_hairless_terrier",
    name: "American Hairless Terrier",
    image: 31,
    group: 2,
    origin: ["US"],
    size: [1],
  },
  {
    code: "american_staffordshire_terrier",
    name: "American Staffordshire Terrier",
    image: 14,
    group: 2,
    origin: ["US"],
    size: [2],
  },
  {
    code: "anatolian_shepherd_dog",
    name: "Anatolian Shepherd Dog",
    image: 41,
    group: 6,
    origin: ["TR"],
    size: [3],
  },
  {
    code: "australian_cattle_dog",
    name: "Australian Cattle Dog",
    image: 404,
    group: 5,
    origin: ["AU"],
    size: [2],
  },
  {
    code: "australian_kelpie",
    name: "Australian Kelpie",
    image: 405,
    group: 5,
    origin: ["AU"],
    size: [2],
  },
  {
    code: "australian_shepherd",
    name: "Australian Shepherd",
    image: 411,
    group: 5,
    origin: ["US"],
    size: [2],
  },
  {
    code: "australian_silky_terrier",
    name: "Australian Silky Terrier",
    image: 412,
    group: 1,
    origin: ["AU"],
    size: [1],
  },
  {
    code: "australian_stumpy_tail_cattle_dog",
    name: "Australian Stumpy Tail Cattle Dog",
    image: 413,
    group: 5,
    origin: ["AU"],
    size: [2],
  },
  {
    code: "australian_terrier",
    name: "Australian Terrier",
    image: 414,
    group: 2,
    origin: ["AU"],
    size: [1],
  },
  {
    code: "azawakh",
    name: "Azawakh",
    image: 422,
    group: 4,
    origin: ["ML", "DZ", "NE", "BF"],
    size: [3],
  },
  {
    code: "basenji",
    name: "Basenji",
    image: 425,
    group: 4,
    origin: ["CD"],
    size: [2],
  },
  {
    code: "basset_fauve_de_bretagne",
    name: "Basset Fauve de Bretagne",
    image: 434,
    group: 4,
    origin: ["FR"],
    size: [1],
  },
  {
    code: "basset_hound",
    name: "Basset Hound",
    image: 442,
    group: 4,
    origin: ["FR", "GB"],
    size: [1],
  },
  {
    code: "beagle",
    name: "Beagle",
    image: 407,
    group: 4,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "bearded_collie",
    name: "Bearded Collie",
    image: 409,
    group: 5,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "beauceron",
    name: "Beauceron",
    image: 410,
    group: 5,
    origin: ["FR"],
    size: [3],
  },
  {
    code: "bedlington_terrier",
    name: "Bedlington Terrier",
    image: 416,
    group: 2,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "belgian_shepherd_dog",
    name: "Belgian Shepherd Dog",
    image: 417,
    group: 5,
    origin: ["BE"],
    size: [2],
    variants: [
      {
        key: "groenendael",
        label: "Groenendael",
        image: 417,
        group: 5,
        size: [2],
      },
      {
        key: "laekenois",
        label: "Laekenois",
        image: 418,
        group: 5,
        size: [2],
      },
      {
        key: "malinois",
        label: "Malinois",
        image: 419,
        group: 5,
        size: [2],
      },
      {
        key: "tervueren",
        label: "Tervueren",
        image: 420,
        group: 5,
        size: [2],
      },
    ],
  },
  {
    code: "bergamasco_shepherd_dog",
    name: "Bergamasco Shepherd Dog",
    image: 426,
    group: 5,
    origin: ["IT"],
    size: [2],
  },
  {
    code: "bernese_mountain_dog",
    name: "Bernese Mountain Dog",
    image: 430,
    group: 6,
    origin: ["CH"],
    size: [2, 3],
  },
  {
    code: "bichon_frise",
    name: "Bichon Frise",
    image: 436,
    group: 1,
    origin: ["BE", "ES"],
    size: [1],
  },
  {
    code: "black_and_tan_coonhound",
    name: "Black and Tan Coonhound",
    image: 438,
    group: 4,
    origin: ["AT", "US"],
    size: [2],
  },
  {
    code: "bloodhound",
    name: "Bloodhound",
    image: 450,
    group: 4,
    origin: ["BE", "FR", "GB"],
    size: [3],
  },
  {
    code: "bluetick_coonhound",
    name: "Bluetick Coonhound",
    image: 352,
    group: 4,
    origin: ["US"],
    size: [2],
  },
  {
    code: "bolognese",
    name: "Bolognese",
    image: 355,
    group: 1,
    origin: ["IT"],
    size: [1],
  },
  {
    code: "border_collie",
    name: "Border Collie",
    image: 361,
    group: 5,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "border_terrier",
    name: "Border Terrier",
    image: 362,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "borzoi",
    name: "Borzoi",
    image: 363,
    group: 4,
    origin: ["RU"],
    size: [3],
  },
  {
    code: "boston_terrier",
    name: "Boston Terrier",
    image: 365,
    group: 7,
    origin: ["US"],
    size: [1],
  },
  {
    code: "bouvier_des_flandres",
    name: "Bouvier des Flandres",
    image: 372,
    group: 5,
    origin: ["BE"],
    size: [3],
  },
  {
    code: "boxer",
    name: "Boxer",
    image: 373,
    group: 6,
    origin: ["DE"],
    size: [2],
  },
  {
    code: "bracco_italiano",
    name: "Bracco Italiano",
    image: 375,
    group: 3,
    origin: ["IT"],
    size: [2],
  },
  {
    code: "briard",
    name: "Briard",
    image: 392,
    group: 5,
    origin: ["FR"],
    size: [2],
  },
  {
    code: "british_bulldog",
    name: "British Bulldog",
    image: 360,
    group: 7,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "brittany",
    name: "Brittany",
    image: 394,
    group: 3,
    origin: ["FR"],
    size: [2],
  },
  {
    code: "bull_terrier",
    name: "Bull Terrier",
    image: 358,
    group: 2,
    origin: ["GB"],
    size: [1, 2],
    variants: [
      {
        key: "miniature",
        label: "Miniature",
        image: 359,
        group: 2,
        origin: ["GB"],
        size: [1],
      },
    ],
  },
  {
    code: "bullmastiff",
    name: "Bullmastiff",
    image: 366,
    group: 6,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "cairn_terrier",
    name: "Cairn Terrier",
    image: 369,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "canaan_dog",
    name: "Canaan Dog",
    image: 370,
    group: 7,
    origin: ["MI"],
    size: [2],
  },
  {
    code: "canadian_eskimo_dog",
    name: "Canadian Eskimo Dog",
    image: 376,
    group: 6,
    origin: ["CA"],
    size: [2],
  },
  {
    code: "cane_corso",
    name: "Cane Corso",
    image: 377,
    group: 6,
    origin: ["IT"],
    size: [3],
  },
  {
    code: "caucasian_shepherd_dog",
    name: "Caucasian Shepherd Dog",
    image: 390,
    group: 6,
    origin: ["GE", "RU", "SU"],
    size: [3],
  },
  {
    code: "cavalier_king_charles_spaniel",
    name: "Cavalier King Charles Spaniel",
    image: 396,
    group: 1,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "central_asian_shepherd_dog",
    name: "Central Asian Shepherd Dog",
    image: 397,
    group: 6,
    origin: ["SU"],
    size: [2],
  },
  {
    code: "cesky_terrier",
    name: "Cesky Terrier",
    image: 399,
    group: 2,
    origin: ["CZ"],
    size: [1],
  },
  {
    code: "chesapeake_bay_retriever",
    name: "Chesapeake Bay Retriever",
    image: 400,
    group: 3,
    origin: ["US"],
    size: [2],
  },
  {
    code: "chihuahua",
    name: "Chihuahua",
    image: 307,
    group: 1,
    size: [1],
    origin: ["MX"],
    variants: [
      {
        key: "long_coat",
        label: "Long Coat",
        group: 1,
        origin: ["MX"],
      },
      {
        key: "smooth_coat",
        label: "Smooth Coat",
        group: 1,
        origin: ["MX"],
      },
    ],
  },
  {
    code: "chinese_crested_dog",
    name: "Chinese Crested Dog",
    image: 310,
    group: 1,
    origin: ["CN"],
    size: [1],
  },
  {
    code: "chow_chow",
    name: "Chow Chow",
    image: 319,
    group: 7,
    origin: ["CN"],
    size: [2],
  },
  {
    code: "cirneco_dell_etna",
    name: "Cirneco Dell'Etna",
    image: 327,
    group: 4,
    origin: ["IT"],
    size: [2],
  },
  {
    code: "clumber_spaniel",
    name: "Clumber Spaniel",
    image: 328,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "cocker_spaniel",
    name: "Cocker Spaniel",
    image: 323,
    group: 3,
    origin: ["GB"],
    size: [1, 2],
    variants: [
      {
        key: "american",
        label: "American",
        image: 23,
        group: 3,
        origin: ["US"],
        size: [1],
      },
    ],
  },
  {
    code: "collie",
    name: "Collie",
    image: 329,
    group: 5,
    origin: ["GB"],
    size: [2],
    variants: [
      {
        key: "rough",
        label: "Rough",
        image: 329,
        group: 5,
        origin: ["GB"],
      },
      {
        key: "smooth",
        label: "Smooth",
        image: 330,
        group: 5,
        origin: ["GB"],
      },
    ],
  },
  {
    code: "coton_de_tulear",
    name: "Coton De Tulear",
    image: 336,
    group: 1,
    origin: ["MG"],
    size: [1],
  },
  {
    code: "curly_coated_retriever",
    name: "Curly Coated Retriever",
    image: 339,
    group: 3,
    origin: ["GB"],
    size: [3],
  },
  {
    code: "dachshund",
    name: "Dachshund",
    image: 347,
    group: 4,
    origin: ["DE"],
    size: [1],
    variants: [
      {
        key: "long_haired",
        label: "Long Haired",
        group: 4,
        origin: ["DE"],
      },
      {
        key: "miniature_long_haired",
        label: "Miniature Long Haired",
        group: 4,
        origin: ["DE"],
      },
      {
        key: "miniature_smooth_haired",
        label: "Miniature Smooth Haired",
        group: 4,
        origin: ["DE"],
      },
      {
        key: "miniature_wire_haired",
        label: "Miniature Wire Haired",
        group: 4,
        origin: ["DE"],
      },
      {
        key: "smooth_haired",
        label: "Smooth Haired",
        group: 4,
        origin: ["DE"],
      },
      {
        key: "wire_haired",
        label: "Wire Haired",
        group: 4,
        origin: ["DE"],
      },
    ],
  },
  {
    code: "dachshund_kaninchen",
    name: "Dachshund Kaninchen",
    image: 451,
    group: 4,
    origin: ["DE"],
    size: [1],
    variants: [
      {
        key: "long_haired",
        label: "Long Haired",
        group: 4,
        origin: ["DE"],
        size: [1],
      },
      {
        key: "smooth_haired",
        label: "Smooth Haired",
        group: 4,
        origin: ["DE"],
        size: [1],
      },
      {
        key: "wire_haired",
        label: "Wire Haired",
        group: 4,
        origin: ["DE"],
        size: [1],
      },
    ],
  },
  {
    code: "dalmatian",
    name: "Dalmatian",
    image: 348,
    group: 7,
    origin: ["HR"],
    size: [2],
  },
  {
    code: "dandie_dinmont_terrier",
    name: "Dandie Dinmont Terrier",
    image: 349,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "deerhound",
    name: "Deerhound",
    image: 62,
    group: 4,
    origin: ["GB"],
    size: [3],
  },
  {
    code: "dobermann",
    name: "Dobermann",
    image: 302,
    group: 6,
    origin: ["DE"],
    size: [3],
  },
  {
    code: "dogue_de_bordeaux",
    name: "Dogue de Bordeaux",
    image: 304,
    group: 6,
    origin: ["FR"],
    size: [3],
  },
  {
    code: "dutch_shepherd_dog",
    name: "Dutch Shepherd Dog",
    image: 313,
    group: 5,
    origin: ["NL"],
    size: [2],
  },
  {
    code: "english_setter",
    name: "English Setter",
    image: 332,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "english_springer_spaniel",
    name: "English Springer Spaniel",
    image: 334,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "english_toy_terrier",
    name: "English Toy Terrier",
    image: 335,
    group: 1,
    origin: ["GB"],
    size: [1],
    variants: [
      {
        key: "black_and_tan",
        label: "Black and Tan",
        image: 335,
        group: 1,
        origin: ["GB"],
        size: [1],
      },
    ],
  },
  {
    code: "estrela_mountain_dog",
    name: "Estrela Mountain Dog",
    image: 344,
    group: 6,
    origin: ["PT"],
    size: [3],
  },
  {
    code: "eurasier",
    name: "Eurasier",
    image: 345,
    group: 7,
    origin: ["DE"],
    size: [2],
  },
  {
    code: "field_spaniel",
    name: "Field Spaniel",
    image: 251,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "finnish_lapphund",
    name: "Finnish Lapphund",
    image: 254,
    group: 5,
    origin: ["FI"],
    size: [2],
  },
  {
    code: "finnish_spitz",
    name: "Finnish Spitz",
    image: 255,
    group: 4,
    origin: ["FI"],
    size: [2],
  },
  {
    code: "flat_coated_retriever",
    name: "Flat Coated Retriever",
    image: 261,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "fox_terrier",
    name: "Fox Terrier",
    image: 263,
    group: 2,
    origin: ["GB"],
    size: [1, 2],
    variants: [
      {
        key: "smooth",
        label: "Smooth",
        image: 263,
        group: 2,
        origin: ["GB"],
        size: [2],
      },
      {
        key: "wire",
        label: "Wire",
        image: 264,
        group: 2,
        origin: ["GB"],
        size: [1],
      },
    ],
  },
  {
    code: "foxhound",
    name: "Foxhound",
    image: 325,
    group: 4,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "french_bulldog",
    name: "French Bulldog",
    image: 271,
    group: 7,
    origin: ["FR"],
    size: [1],
  },
  {
    code: "german_hunting_terrier",
    name: "German Hunting Terrier",
    image: 230,
    group: 2,
    origin: ["DE"],
    size: [2],
  },
  {
    code: "german_pinscher",
    name: "German Pinscher",
    image: 282,
    group: 6,
    origin: ["DE"],
    size: [2],
  },
  {
    code: "german_shepherd_dog",
    name: "German Shepherd Dog",
    image: 284,
    group: 5,
    origin: ["DE"],
    size: [2],
    variants: [
      {
        key: "stock_coat",
        label: "Stock Coat",
        group: 5,
      },
      {
        key: "long_stock_coat",
        label: "Long Stock Coat",
        group: 5,
      },
    ],
  },
  {
    code: "german_shorthaired_pointer",
    name: "German Shorthaired Pointer",
    image: 285,
    group: 3,
    origin: ["DE"],
    size: [2],
  },
  {
    code: "german_spitz",
    name: "German Spitz",
    image: 292,
    group: 7,
    origin: ["DE"],
    size: [1, 2],
    variants: [
      {
        key: "klein",
        label: "Klein",
        group: 7,
        origin: ["DE"],
        size: [1],
      },
      {
        key: "mittel",
        label: "Mittel",
        group: 7,
        origin: ["DE"],
        size: [1],
      },
    ],
  },
  {
    code: "german_wirehaired_pointer",
    name: "German Wirehaired Pointer",
    image: 293,
    group: 3,
    origin: ["DE"],
    size: [2],
  },
  {
    code: "glen_of_imaal_terrier",
    name: "Glen of Imaal Terrier",
    image: 295,
    group: 2,
    origin: ["IE", "GB"],
    size: [2],
  },
  {
    code: "golden_retriever",
    name: "Golden Retriever",
    image: 256,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "gordon_setter",
    name: "Gordon Setter",
    image: 257,
    group: 3,
    origin: ["GB"],
    size: [3],
  },
  {
    code: "grand_basset_griffon_vendeen",
    name: "Grand Basset Griffon Vendeen",
    image: 266,
    group: 4,
    origin: ["FR"],
    size: [2],
  },
  {
    code: "great_dane",
    name: "Great Dane",
    image: 267,
    group: 7,
    origin: ["DE"],
    size: [3],
  },
  {
    code: "greyhound",
    name: "Greyhound",
    image: 277,
    group: 4,
    origin: ["GB"],
    size: [3],
  },
  {
    code: "griffon_bruxellois",
    name: "Griffon Bruxellois",
    image: 279,
    group: 1,
    origin: ["BE"],
    size: [1],
  },
  {
    code: "hamiltonstovare",
    name: "Hamiltonstovare",
    image: 287,
    group: 4,
    origin: ["SE"],
    size: [2],
  },
  {
    code: "harrier",
    name: "Harrier",
    image: 289,
    group: 4,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "havanese",
    name: "Havanese",
    image: 290,
    group: 1,
    origin: ["CU"],
    size: [1],
  },
  {
    code: "hungarian_vizsla",
    name: "Hungarian Vizsla",
    image: 27,
    group: 3,
    origin: ["HU"],
    size: [2],
  },
  {
    code: "hungarian_wirehaired_vizsla",
    name: "Hungarian Wirehaired Vizsla",
    image: 452,
    group: 3,
    origin: ["HU"],
    size: [2],
  },
  {
    code: "ibizan_hound",
    name: "Ibizan Hound",
    image: 208,
    group: 4,
    origin: ["ES"],
    size: [3],
  },
  {
    code: "icelandic_sheepdog",
    name: "Icelandic Sheepdog",
    image: 209,
    group: 5,
    origin: ["IS"],
    size: [1],
  },
  {
    code: "irish_red_and_white_setter",
    name: "Irish Red and White Setter",
    image: 216,
    group: 3,
    origin: ["IE", "GB"],
    size: [2],
  },
  {
    code: "irish_setter",
    name: "Irish Setter",
    image: 217,
    group: 3,
    origin: ["IE", "GB"],
    size: [3],
  },
  {
    code: "irish_terrier",
    name: "Irish Terrier",
    image: 218,
    group: 2,
    origin: ["IE", "GB"],
    size: [2],
  },
  {
    code: "irish_water_spaniel",
    name: "Irish Water Spaniel",
    image: 219,
    group: 3,
    origin: ["IE", "GB"],
    size: [2],
  },
  {
    code: "irish_wolfhound",
    name: "Irish Wolfhound",
    image: 220,
    group: 4,
    origin: ["IE"],
    size: [3],
  },
  {
    code: "italian_greyhound",
    name: "Italian Greyhound",
    image: 228,
    group: 1,
    origin: ["IT"],
    size: [1],
  },
  {
    code: "italian_spinone",
    name: "Italian Spinone",
    image: 68,
    group: 3,
    origin: ["IT"],
    size: [2],
  },
  {
    code: "jack_russell_terrier",
    name: "Jack Russell Terrier",
    image: 229,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "japanese_chin",
    name: "Japanese Chin",
    image: 237,
    group: 1,
    origin: ["JP"],
    size: [1],
  },
  {
    code: "japanese_spitz",
    name: "Japanese Spitz",
    image: 238,
    group: 7,
    origin: ["JP"],
    size: [1],
  },
  {
    code: "kangal_shepherd_dog",
    name: "Kangal Shepherd Dog",
    image: 246,
    group: 6,
    origin: ["TR"],
    size: [3],
  },
  {
    code: "karelian_bear_dog",
    name: "Karelian Bear Dog",
    image: 249,
    group: 7,
    origin: ["FI"],
    size: [2],
  },
  {
    code: "keeshond",
    name: "Keeshond",
    image: 201,
    group: 7,
    origin: ["DE", "NL"],
    size: [2],
  },
  {
    code: "kerry_blue_terrier",
    name: "Kerry Blue Terrier",
    image: 203,
    group: 2,
    origin: ["IE", "GB"],
    size: [2],
  },
  {
    code: "king_charles_spaniel",
    name: "King Charles Spaniel",
    image: 204,
    group: 1,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "komondor",
    name: "Komondor",
    image: 213,
    group: 5,
    origin: ["HU"],
    size: [2],
  },
  {
    code: "kuvasz",
    name: "Kuvasz",
    image: 224,
    group: 5,
    origin: ["HU"],
    size: [3],
  },
  {
    code: "labrador_retriever",
    name: "Labrador Retriever",
    image: 232,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "lagotto_romagnolo",
    name: "Lagotto Romagnolo",
    image: 233,
    group: 3,
    origin: ["IT"],
    size: [2],
  },
  {
    code: "lakeland_terrier",
    name: "Lakeland Terrier",
    image: 234,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "landseer",
    name: "Landseer",
    image: 241,
    group: 6,
    origin: ["CA"],
    size: [3],
    variants: [
      {
        key: "european_continental_type",
        label: "European Continental Type",
        group: 6,
        origin: ["CA"],
        size: [3],
      },
    ],
  },
  {
    code: "large_munsterlander",
    name: "Large Munsterlander",
    image: 192,
    group: 3,
    origin: ["DE"],
    size: [2],
  },
  {
    code: "leonberger",
    name: "Leonberger",
    image: 243,
    group: 6,
    origin: ["DE"],
    size: [3],
  },
  {
    code: "lhasa_apso",
    name: "Lhasa Apso",
    image: 244,
    group: 7,
    origin: ["TI"],
    size: [1],
  },
  {
    code: "lowchen",
    name: "Lowchen",
    image: 152,
    group: 1,
    origin: ["FR", "DE"],
    size: [1],
  },
  {
    code: "maltese",
    name: "Maltese",
    image: 154,
    group: 1,
    origin: ["IT", "MT"],
    size: [1],
  },
  {
    code: "manchester_terrier",
    name: "Manchester Terrier",
    image: 155,
    group: 2,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "maremma_sheepdog",
    name: "Maremma Sheepdog",
    image: 161,
    group: 5,
    origin: ["IT"],
    size: [3],
  },
  {
    code: "mastiff",
    name: "Mastiff",
    image: 331,
    group: 6,
    origin: ["GB"],
    size: [3],
  },
  {
    code: "miniature_pinscher",
    name: "Miniature Pinscher",
    image: 172,
    group: 1,
    origin: ["DE"],
    size: [1],
  },
  {
    code: "neapolitan_mastiff",
    name: "Neapolitan Mastiff",
    image: 194,
    group: 6,
    origin: ["IT"],
    size: [3],
  },
  {
    code: "newfoundland",
    name: "Newfoundland",
    image: 195,
    group: 6,
    origin: ["CA"],
    size: [3],
  },
  {
    code: "norfolk_terrier",
    name: "Norfolk Terrier",
    image: 157,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "norwegian_buhund",
    name: "Norwegian Buhund",
    image: 160,
    group: 5,
    origin: ["NO"],
    size: [2],
  },
  {
    code: "norwegian_elkhound",
    name: "Norwegian Elkhound",
    image: 166,
    group: 4,
    origin: ["NO"],
    size: [2],
  },
  {
    code: "norwich_terrier",
    name: "Norwich Terrier",
    image: 168,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "nova_scotia_duck_tolling_retriever",
    name: "Nova Scotia Duck Tolling Retriever",
    image: 169,
    group: 3,
    origin: ["CA"],
    size: [2],
  },
  {
    code: "old_english_sheepdog",
    name: "Old English Sheepdog",
    image: 177,
    group: 5,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "otterhound",
    name: "Otterhound",
    image: 187,
    group: 4,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "papillon",
    name: "Papillon",
    image: 189,
    group: 1,
    origin: ["BE", "FR"],
    size: [1],
    variants: [
      {
        key: "phalene",
        label: "Phalene",
        image: 106,
        origin: ["BE", "FR"],
      },
    ],
  },
  {
    code: "parson_russell_terrier",
    name: "Parson Russell Terrier",
    image: 190,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "pekingese",
    name: "Pekingese",
    image: 197,
    group: 1,
    origin: ["CN"],
    size: [1],
  },
  {
    code: "peruvian_hairless_dog",
    name: "Peruvian Hairless Dog",
    image: 200,
    group: 7,
    origin: ["PE"],
    size: [1, 2],
    variants: [
      {
        key: "large",
        label: "Large",
        group: 7,
        origin: ["PE"],
        size: [2],
      },
      {
        key: "medium",
        label: "Medium",
        group: 7,
        origin: ["PE"],
        size: [2],
      },
      {
        key: "small",
        label: "Small",
        group: 7,
        origin: ["PE"],
        size: [1],
      },
    ],
  },
  {
    code: "petit_basset_griffon_vendeen",
    name: "Petit Basset Griffon Vendeen",
    image: 441,
    group: 4,
    origin: ["FR"],
    size: [1],
  },
  {
    code: "pharaoh_hound",
    name: "Pharaoh Hound",
    image: 107,
    group: 4,
    origin: ["MT"],
    size: [2],
  },
  {
    code: "pointer",
    name: "Pointer",
    image: 117,
    group: 3,
    origin: ["GB"],
    size: [3],
  },
  {
    code: "polish_lowland_sheepdog",
    name: "Polish Lowland Sheepdog",
    image: 126,
    group: 5,
    origin: ["PL"],
    size: [2],
  },
  {
    code: "pomeranian",
    name: "Pomeranian",
    image: 128,
    group: 1,
    origin: ["DE", "PU"],
    size: [1],
  },
  {
    code: "poodle",
    name: "Poodle",
    image: 130,
    group: 7,
    origin: ["FR", "DE"],
    size: [1, 2],
    variants: [
      {
        key: "miniature",
        label: "Miniature",
        group: 7,
        origin: ["FR"],
        size: [1],
      },
      {
        key: "standard",
        label: "Standard",
        group: 7,
        origin: ["FR"],
        size: [2],
      },
      {
        key: "toy",
        label: "Toy",
        group: 7,
        origin: ["FR"],
        size: [1],
      },
    ],
  },
  {
    code: "portuguese_podengo",
    name: "Portuguese Podengo",
    image: 137,
    group: 4,
    origin: ["PT"],
    size: [1, 2, 3],
    variants: [
      {
        key: "large_smooth_haired",
        label: "Large Smooth Haired",
        group: 4,
        origin: ["PT"],
        size: [3],
      },
      {
        key: "large_wire_haired",
        label: "Large Wire Haired",
        group: 4,
        origin: ["PT"],
        size: [3],
      },
      {
        key: "medium_smooth_haired",
        label: "Medium Smooth Haired",
        group: 4,
        origin: ["PT"],
        size: [2],
      },
      {
        key: "medium_wire_haired",
        label: "Medium Wire Haired",
        group: 4,
        origin: ["PT"],
        size: [2],
      },
      {
        key: "small_smooth_haired",
        label: "Small Smooth Haired",
        group: 4,
        origin: ["PT"],
        size: [1],
      },
      {
        key: "small_wire_haired",
        label: "Small Wire Haired",
        group: 4,
        origin: ["PT"],
        size: [1],
      },
    ],
  },
  {
    code: "portuguese_water_dog",
    name: "Portuguese Water Dog",
    image: 139,
    group: 6,
    origin: ["PT"],
    size: [2],
  },
  {
    code: "pug",
    name: "Pug",
    image: 148,
    group: 1,
    origin: ["CN"],
    size: [1],
  },
  {
    code: "puli",
    name: "Puli",
    image: 149,
    group: 5,
    origin: ["HU"],
    size: [2],
  },
  {
    code: "pumi",
    name: "Pumi",
    image: 150,
    group: 5,
    origin: ["HU"],
    size: [2],
  },
  {
    code: "pyrenean_mastiff",
    name: "Pyrenean Mastiff",
    image: 102,
    group: 6,
    origin: ["ES"],
    size: [3],
  },
  {
    code: "pyrenean_mountain_dog",
    name: "Pyrenean Mountain Dog",
    image: 268,
    group: 6,
    origin: ["FR"],
    size: [3],
  },
  {
    code: "pyrenean_sheepdog_longhaired",
    name: "Pyrenean Sheepdog Longhaired",
    image: 103,
    group: 5,
    origin: ["FR"],
    size: [2],
  },
  {
    code: "rhodesian_ridgeback",
    name: "Rhodesian Ridgeback",
    image: 121,
    group: 4,
    origin: ["ZW", "ZA"],
    size: [3],
  },
  {
    code: "rottweiler",
    name: "Rottweiler",
    image: 122,
    group: 6,
    origin: ["DE"],
    size: [2, 3],
  },
  {
    code: "russian_black_terrier",
    name: "Russian Black Terrier",
    image: 446,
    group: 6,
    origin: ["RU", "SU"],
    size: [3],
  },
  {
    code: "russian_toy",
    name: "Russian Toy",
    image: 124,
    group: 1,
    origin: ["RU", "SU"],
    size: [1],
    variants: [
      {
        key: "long_haired",
        label: "Long Haired",
        group: 1,
        origin: ["RU", "SU"],
        size: [1],
      },
      {
        key: "smooth_haired",
        label: "Smooth Haired",
        group: 1,
        origin: ["RU", "SU"],
        size: [1],
      },
    ],
  },
  {
    code: "saluki",
    name: "Saluki",
    image: 141,
    group: 4,
    origin: ["MI"],
    size: [2],
  },
  {
    code: "samoyed",
    name: "Samoyed",
    image: 142,
    group: 6,
    origin: ["RU"],
    size: [2],
  },
  {
    code: "schipperke",
    name: "Schipperke",
    image: 52,
    group: 7,
    origin: ["BE"],
    size: [1],
  },
  {
    code: "schnauzer",
    name: "Schnauzer",
    image: 53,
    group: 6,
    origin: ["DE"],
    size: [1, 2],
    variants: [
      {
        key: "giant",
        label: "Giant",
        group: 6,
        origin: ["DE"],
        size: [2],
      },
      {
        key: "miniature",
        label: "Miniature",
        group: 6,
        origin: ["DE"],
        size: [1],
      },
    ],
  },
  {
    code: "scottish_terrier",
    name: "Scottish Terrier",
    image: 63,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "sealyham_terrier",
    name: "Sealyham Terrier",
    image: 64,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "shar_pei",
    name: "Shar Pei",
    image: 74,
    group: 7,
    origin: ["CN"],
    size: [2],
  },
  {
    code: "shetland_sheepdog",
    name: "Shetland Sheepdog",
    image: 75,
    group: 5,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "shiba_inu",
    name: "Shiba Inu",
    image: 81,
    group: 6,
    origin: ["JP"],
    size: [2],
  },
  {
    code: "shih_tzu",
    name: "Shih Tzu",
    image: 82,
    group: 7,
    origin: ["CN", "TI"],
    size: [1],
  },
  {
    code: "siberian_husky",
    name: "Siberian Husky",
    image: 85,
    group: 6,
    origin: ["RU"],
    size: [2],
  },
  {
    code: "skye_terrier",
    name: "Skye Terrier",
    image: 92,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "sloughi",
    name: "Sloughi",
    image: 93,
    group: 4,
    origin: ["MI"],
    size: [3],
  },
  {
    code: "soft_coated_wheaten_terrier",
    name: "Soft Coated Wheaten Terrier",
    image: 59,
    group: 2,
    origin: ["IE", "GB"],
    size: [2],
  },
  {
    code: "spanish_mastiff",
    name: "Spanish Mastiff",
    image: 66,
    group: 6,
    origin: ["ES"],
    size: [3],
  },
  {
    code: "spanish_water_dog",
    name: "Spanish Water Dog",
    image: 67,
    group: 3,
    origin: ["ES"],
    size: [2],
  },
  {
    code: "st_bernard",
    name: "St Bernard",
    image: 70,
    group: 6,
    origin: ["IT", "CH"],
    size: [3],
  },
  {
    code: "staffordshire_bull_terrier",
    name: "Staffordshire Bull Terrier",
    image: 77,
    group: 2,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "sussex_spaniel",
    name: "Sussex Spaniel",
    image: 80,
    group: 3,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "swedish_lapphund",
    name: "Swedish Lapphund",
    image: 86,
    group: 5,
    origin: ["SE"],
    size: [2],
  },
  {
    code: "swedish_vallhund",
    name: "Swedish Vallhund",
    image: 87,
    group: 5,
    origin: ["SE"],
    size: [1],
  },
  {
    code: "tatra_shepherd_dog",
    name: "Tatra Shepherd Dog",
    image: 127,
    group: 5,
    origin: ["PL"],
    size: [3],
  },
  {
    code: "tenterfield_terrier",
    name: "Tenterfield Terrier",
    image: 98,
    group: 2,
    origin: ["AU"],
    size: [1],
  },
  {
    code: "tibetan_mastiff",
    name: "Tibetan Mastiff",
    image: 6,
    group: 6,
    origin: ["TI"],
    size: [3],
  },
  {
    code: "tibetan_spaniel",
    name: "Tibetan Spaniel",
    image: 7,
    group: 1,
    origin: ["TI"],
    size: [1],
  },
  {
    code: "tibetan_terrier",
    name: "Tibetan Terrier",
    image: 8,
    group: 7,
    origin: ["TI"],
    size: [2],
  },
  {
    code: "tornjak",
    name: "Tornjak",
    image: 9,
    group: 6,
    origin: ["BA", "HR"],
    size: [2],
  },
  {
    code: "weimaraner",
    name: "Weimaraner",
    image: 29,
    group: 3,
    origin: ["DE"],
    size: [2],
    variants: [
      {
        key: "long-haired",
        label: "Long-haired",
        group: 3,
      },
    ],
  },
  {
    code: "welsh_corgi",
    name: "Welsh Corgi",
    image: 30,
    group: 5,
    origin: ["GB"],
    size: [1],
    variants: [
      {
        key: "cardigan",
        label: "Cardigan",
        image: 30,
        group: 5,
        origin: ["GB"],
        size: [1],
      },
      {
        key: "pembroke",
        label: "Pembroke",
        image: 36,
        group: 5,
        origin: ["GB"],
        size: [1],
      },
    ],
  },
  {
    code: "welsh_springer_spaniel",
    name: "Welsh Springer Spaniel",
    image: 38,
    group: 3,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "welsh_terrier",
    name: "Welsh Terrier",
    image: 39,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "west_highland_white_terrier",
    name: "West Highland White Terrier",
    image: 40,
    group: 2,
    origin: ["GB"],
    size: [1],
  },
  {
    code: "whippet",
    name: "Whippet",
    image: 49,
    group: 4,
    origin: ["GB"],
    size: [2],
  },
  {
    code: "white_swiss_shepherd_dog",
    name: "White Swiss Shepherd Dog",
    image: 50,
    group: 5,
    origin: ["CH"],
    size: [2],
  },
  {
    code: "wirehaired_slovakian_pointer",
    name: "Wirehaired Slovakian Pointer",
    image: 95,
    group: 3,
    origin: ["SK"],
    size: [2],
  },
  {
    code: "xoloitzcuintle",
    name: "Xoloitzcuintle",
    image: 163,
    group: 7,
    origin: ["MX"],
    size: [1, 2],
    variants: [
      {
        key: "intermediate",
        label: "Intermediate",
        group: 7,
        origin: ["MX"],
        size: [2],
      },
      {
        key: "miniature",
        label: "Miniature",
        group: 7,
        origin: ["MX"],
        size: [1],
      },
      {
        key: "standard",
        label: "Standard",
        group: 7,
        origin: ["MX"],
        size: [2],
      },
    ],
  },
  {
    code: "yakutian_laika",
    name: "Yakutian Laika",
    image: 453,
    group: 6,
    origin: ["RU"],
    size: [2, 3],
  },
  {
    code: "yorkshire_terrier",
    name: "Yorkshire Terrier",
    image: 454,
    group: 1,
    origin: ["GB"],
    size: [1],
  },
] as const;

export type BreedCode = typeof breeds[number]["code"];
