export const breeds = [
  {
    code: "affenpinscher",
    latitude: 0.0,
    longitude: 0.0,
    name: "Affenpinscher",
    image: 1,
  },
  {
    code: "afghan_hound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Afghan Hound",
    image: 2,
  },
  {
    code: "airedale_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Airedale Terrier",
    image: 4,
  },
  {
    code: "akita",
    latitude: 0.0,
    longitude: 0.0,
    name: "Akita",
    image: 11,
    variants: [
      {
        key: "japanese",
        label: "Japanese",
      },
    ],
  },
  {
    code: "alaskan_malamute",
    latitude: 0.0,
    longitude: 0.0,
    name: "Alaskan Malamute",
    image: 14,
  },
  {
    code: "american_hairless_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "American Hairless Terrier",
    image: 31,
  },
  {
    code: "american_staffordshire_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "American Staffordshire Terrier",
    image: 14,
  },
  {
    code: "anatolian_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Anatolian Shepherd Dog",
    image: 41,
  },
  {
    code: "australian_cattle_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Australian Cattle Dog",
    image: 404,
  },
  {
    code: "australian_kelpie",
    latitude: 0.0,
    longitude: 0.0,
    name: "Australian Kelpie",
    image: 405,
  },
  {
    code: "australian_shepherd",
    latitude: 0.0,
    longitude: 0.0,
    name: "Australian Shepherd",
    image: 411,
  },
  {
    code: "australian_silky_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Australian Silky Terrier",
    image: 412,
  },
  {
    code: "australian_stumpy_tail_cattle_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Australian Stumpy Tail Cattle Dog",
    image: 413,
  },
  {
    code: "australian_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Australian Terrier",
    image: 414,
  },
  {
    code: "azawakh",
    latitude: 0.0,
    longitude: 0.0,
    name: "Azawakh",
    image: 422,
  },
  {
    code: "basenji",
    latitude: 0.0,
    longitude: 0.0,
    name: "Basenji",
    image: 425,
  },
  {
    code: "basset_fauve_de_bretagne",
    latitude: 0.0,
    longitude: 0.0,
    name: "Basset Fauve de Bretagne",
    image: 434,
  },
  {
    code: "basset_hound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Basset Hound",
    image: 442,
  },
  {
    code: "beagle",
    latitude: 0.0,
    longitude: 0.0,
    name: "Beagle",
    image: 407,
  },
  {
    code: "bearded_collie",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bearded Collie",
    image: 409,
  },
  {
    code: "beauceron",
    latitude: 0.0,
    longitude: 0.0,
    name: "Beauceron",
    image: 410,
  },
  {
    code: "bedlington_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bedlington Terrier",
    image: 416,
  },
  {
    code: "belgian_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Belgian Shepherd Dog",
    image: 417,
    variants: [
      {
        key: "groenendael",
        label: "Groenendael",
        image: 417,
      },
      {
        key: "laekenois",
        label: "Laekenois",
        image: 418,
      },
      {
        key: "malinois",
        label: "Malinois",
        image: 419,
      },
      {
        key: "tervueren",
        label: "Tervueren",
        image: 420,
      },
    ],
  },
  {
    code: "bergamasco_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bergamasco Shepherd Dog",
    image: 426,
  },
  {
    code: "bernese_mountain_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bernese Mountain Dog",
    image: 430,
  },
  {
    code: "bichon_frise",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bichon Frise",
    image: 436,
  },
  {
    code: "black_and_tan_coonhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Black and Tan Coonhound",
    image: 438,
  },
  {
    code: "bloodhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bloodhound",
    image: 450,
  },
  {
    code: "bluetick_coonhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bluetick Coonhound",
    image: 352,
  },
  {
    code: "bolognese",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bolognese",
    image: 355,
  },
  {
    code: "border_collie",
    latitude: 0.0,
    longitude: 0.0,
    name: "Border Collie",
    image: 361,
  },
  {
    code: "border_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Border Terrier",
    image: 362,
  },
  {
    code: "borzoi",
    latitude: 0.0,
    longitude: 0.0,
    name: "Borzoi",
    image: 363,
  },
  {
    code: "boston_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Boston Terrier",
    image: 365
  },
  {
    code: "bouvier_des_flandres",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bouvier des Flandres",
    image: 372,
  },
  {
    code: "boxer",
    latitude: 0.0,
    longitude: 0.0,
    name: "Boxer",
    image: 373,
  },
  {
    code: "bracco_italiano",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bracco Italiano",
    image: 375,
  },
  {
    code: "briard",
    latitude: 0.0,
    longitude: 0.0,
    name: "Briard",
    image: 392,
  },
  {
    code: "british_bulldog",
    latitude: 0.0,
    longitude: 0.0,
    name: "British Bulldog",
    image: 360,
  },
  {
    code: "brittany",
    latitude: 0.0,
    longitude: 0.0,
    name: "Brittany",
    image: 394,
  },
  {
    code: "bull_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bull Terrier",
    image: 358,
    variants: [
      {
        key: "miniature",
        label: "Miniature",
        image: 359,
      },
    ],
  },
  {
    code: "bullmastiff",
    latitude: 0.0,
    longitude: 0.0,
    name: "Bullmastiff",
    image: 366,
  },
  {
    code: "cairn_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Cairn Terrier",
    image: 369,
  },
  {
    code: "canaan_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Canaan Dog",
    image: 370,
  },
  {
    code: "canadian_eskimo_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Canadian Eskimo Dog",
    image: 376,
  },
  {
    code: "cane_corso",
    latitude: 0.0,
    longitude: 0.0,
    name: "Cane Corso",
    image: 377,
  },
  {
    code: "caucasian_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Caucasian Shepherd Dog",
    image: 390,
  },
  {
    code: "cavalier_king_charles_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Cavalier King Charles Spaniel",
    image: 396,
  },
  {
    code: "central_asian_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Central Asian Shepherd Dog",
    image: 397,
  },
  {
    code: "cesky_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Cesky Terrier",
    image: 399,
  },
  {
    code: "chesapeake_bay_retriever",
    latitude: 0.0,
    longitude: 0.0,
    name: "Chesapeake Bay Retriever",
    image: 400,
  },
  {
    code: "chihuahua",
    latitude: 0.0,
    longitude: 0.0,
    name: "Chihuahua",
    image: 307,
    variants: [
      {
        key: "long_coat",
        label: "Long Coat",
      },
      {
        key: "smooth_coat",
        label: "Smooth Coat",
      },
    ],
  },
  {
    code: "chinese_crested_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Chinese Crested Dog",
    image: 310,
  },
  {
    code: "chow_chow",
    latitude: 0.0,
    longitude: 0.0,
    name: "Chow Chow",
    image: 319,
  },
  {
    code: "cirneco_dell_etna",
    latitude: 0.0,
    longitude: 0.0,
    name: "Cirneco Dell'Etna",
    image: 327,
  },
  {
    code: "clumber_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Clumber Spaniel",
    image: 328,
  },
  {
    code: "cocker_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Cocker Spaniel",
    image: 323,
    variants: [
      {
        key: "american",
        label: "American",
        image: 23,
      },
    ],
  },
  {
    code: "collie",
    latitude: 0.0,
    longitude: 0.0,
    name: "Collie",
    image: 329,
    variants: [
      {
        key: "rough",
        label: "Rough",
        image: 329,
      },
      {
        key: "smooth",
        label: "Smooth",
        image: 330,
      },
    ],
  },
  {
    code: "coton_de_tulear",
    latitude: 0.0,
    longitude: 0.0,
    name: "Coton De Tulear",
    image: 336,
  },
  {
    code: "curly_coated_retriever",
    latitude: 0.0,
    longitude: 0.0,
    name: "Curly Coated Retriever",
    image: 339,
  },
  {
    code: "dachshund",
    latitude: 0.0,
    longitude: 0.0,
    name: "Dachshund",
    image: 347,
    variants: [
      {
        key: "long_haired",
        label: "Long Haired",
      },
      {
        key: "miniature_long_haired",
        label: "Miniature Long Haired",
      },
      {
        key: "miniature_smooth_haired",
        label: "Miniature Smooth Haired",
      },
      {
        key: "miniature_wire_haired",
        label: "Miniature Wire Haired",
      },
      {
        key: "smooth_haired",
        label: "Smooth Haired",
      },
      {
        key: "wire_haired",
        label: "Wire Haired",
      },
    ],
  },
  {
    code: "dachshund_kaninchen",
    latitude: 0.0,
    longitude: 0.0,
    name: "Dachshund Kaninchen",
    variants: [
      {
        key: "long_haired",
        label: "Long Haired",
      },
      {
        key: "smooth_haired",
        label: "Smooth Haired",
      },
      {
        key: "wire_haired",
        label: "Wire Haired",
      },
    ],
  },
  {
    code: "dalmatian",
    latitude: 0.0,
    longitude: 0.0,
    name: "Dalmatian",
    image: 348,
  },
  {
    code: "dandie_dinmont_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Dandie Dinmont Terrier",
    image: 349,
  },
  {
    code: "deerhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Deerhound",
  },
  {
    code: "dobermann",
    latitude: 0.0,
    longitude: 0.0,
    name: "Dobermann",
  },
  {
    code: "dogue_de_bordeaux",
    latitude: 0.0,
    longitude: 0.0,
    name: "Dogue de Bordeaux",
  },
  {
    code: "dutch_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Dutch Shepherd Dog",
  },
  {
    code: "english_setter",
    latitude: 0.0,
    longitude: 0.0,
    name: "English Setter",
  },
  {
    code: "english_springer_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "English Springer Spaniel",
  },
  {
    code: "english_toy_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "English Toy Terrier",
    variants: [
      {
        key: "black_and_tan",
        label: "Black and Tan",
      },
    ],
  },
  {
    code: "estrela_mountain_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Estrela Mountain Dog",
  },
  {
    code: "eurasier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Eurasier",
  },
  {
    code: "field_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Field Spaniel",
  },
  {
    code: "finnish_lapphund",
    latitude: 0.0,
    longitude: 0.0,
    name: "Finnish Lapphund",
  },
  {
    code: "finnish_spitz",
    latitude: 0.0,
    longitude: 0.0,
    name: "Finnish Spitz",
  },
  {
    code: "flat_coated_retriever",
    latitude: 0.0,
    longitude: 0.0,
    name: "Flat Coated Retriever",
  },
  {
    code: "fox_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Fox Terrier",
    variants: [
      {
        key: "smooth",
        label: "Smooth",
      },
      {
        key: "wire",
        label: "Wire",
      },
    ],
  },
  {
    code: "foxhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Foxhound",
  },
  {
    code: "french_bulldog",
    latitude: 0.0,
    longitude: 0.0,
    name: "French Bulldog",
  },
  {
    code: "german_hunting_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "German Hunting Terrier",
  },
  {
    code: "german_pinscher",
    latitude: 0.0,
    longitude: 0.0,
    name: "German Pinscher",
  },
  {
    code: "german_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "German Shepherd Dog",
    variants: [
      {
        key: "stock_coat",
        label: "Stock Coat",
      },
      {
        key: "long_stock_coat",
        label: "Long Stock Coat",
      },
    ],
  },
  {
    code: "german_shorthaired_pointer",
    latitude: 0.0,
    longitude: 0.0,
    name: "German Shorthaired Pointer",
  },
  {
    code: "german_spitz",
    latitude: 0.0,
    longitude: 0.0,
    name: "German Spitz",
    variants: [
      {
        key: "klein",
        label: "Klein",
      },
      {
        key: "mittel",
        label: "Mittel",
      },
    ],
  },
  {
    code: "german_wirehaired_pointer",
    latitude: 0.0,
    longitude: 0.0,
    name: "German Wirehaired Pointer",
  },
  {
    code: "glen_of_imaal_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Glen of Imaal Terrier",
  },
  {
    code: "golden_retriever",
    latitude: 0.0,
    longitude: 0.0,
    name: "Golden Retriever",
  },
  {
    code: "gordon_setter",
    latitude: 0.0,
    longitude: 0.0,
    name: "Gordon Setter",
  },
  {
    code: "grand_basset_griffon_vendeen",
    latitude: 0.0,
    longitude: 0.0,
    name: "Grand Basset Griffon Vendeen",
  },
  {
    code: "great_dane",
    latitude: 0.0,
    longitude: 0.0,
    name: "Great Dane",
  },
  {
    code: "greyhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Greyhound",
  },
  {
    code: "griffon_bruxellois",
    latitude: 0.0,
    longitude: 0.0,
    name: "Griffon Bruxellois",
  },
  {
    code: "hamiltonstovare",
    latitude: 0.0,
    longitude: 0.0,
    name: "Hamiltonstovare",
  },
  {
    code: "harrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Harrier",
  },
  {
    code: "havanese",
    latitude: 0.0,
    longitude: 0.0,
    name: "Havanese",
  },
  {
    code: "hungarian_vizsla",
    latitude: 0.0,
    longitude: 0.0,
    name: "Hungarian Vizsla",
  },
  {
    code: "hungarian_wirehaired_vizsla",
    latitude: 0.0,
    longitude: 0.0,
    name: "Hungarian Wirehaired Vizsla",
  },
  {
    code: "ibizan_hound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Ibizan Hound",
  },
  {
    code: "icelandic_sheepdog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Icelandic Sheepdog",
  },
  {
    code: "irish_red_and_white_setter",
    latitude: 0.0,
    longitude: 0.0,
    name: "Irish Red and White Setter",
  },
  {
    code: "irish_setter",
    latitude: 0.0,
    longitude: 0.0,
    name: "Irish Setter",
  },
  {
    code: "irish_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Irish Terrier",
  },
  {
    code: "irish_water_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Irish Water Spaniel",
  },
  {
    code: "irish_wolfhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Irish Wolfhound",
  },
  {
    code: "italian_greyhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Italian Greyhound",
  },
  {
    code: "italian_spinone",
    latitude: 0.0,
    longitude: 0.0,
    name: "Italian Spinone",
  },
  {
    code: "jack_russell_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Jack Russell Terrier",
  },
  {
    code: "japanese_chin",
    latitude: 0.0,
    longitude: 0.0,
    name: "Japanese Chin",
  },
  {
    code: "japanese_spitz",
    latitude: 0.0,
    longitude: 0.0,
    name: "Japanese Spitz",
  },
  {
    code: "kangal_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Kangal Shepherd Dog",
  },
  {
    code: "karelian_bear_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Karelian Bear Dog",
  },
  {
    code: "keeshond",
    latitude: 0.0,
    longitude: 0.0,
    name: "Keeshond",
  },
  {
    code: "kerry_blue_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Kerry Blue Terrier",
  },
  {
    code: "king_charles_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "King Charles Spaniel",
  },
  {
    code: "komondor",
    latitude: 0.0,
    longitude: 0.0,
    name: "Komondor",
  },
  {
    code: "kuvasz",
    latitude: 0.0,
    longitude: 0.0,
    name: "Kuvasz",
  },
  {
    code: "labrador_retriever",
    latitude: 0.0,
    longitude: 0.0,
    name: "Labrador Retriever",
  },
  {
    code: "lagotto_romagnolo",
    latitude: 0.0,
    longitude: 0.0,
    name: "Lagotto Romagnolo",
  },
  {
    code: "lakeland_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Lakeland Terrier",
  },
  {
    code: "landseer",
    latitude: 0.0,
    longitude: 0.0,
    name: "Landseer",
    variants: [
      {
        key: "european_continental_type",
        label: "European Continental Type",
      },
    ],
  },
  {
    code: "large_munsterlander",
    latitude: 0.0,
    longitude: 0.0,
    name: "Large Munsterlander",
  },
  {
    code: "leonberger",
    latitude: 0.0,
    longitude: 0.0,
    name: "Leonberger",
  },
  {
    code: "lhasa_apso",
    latitude: 0.0,
    longitude: 0.0,
    name: "Lhasa Apso",
  },
  {
    code: "lowchen",
    latitude: 0.0,
    longitude: 0.0,
    name: "Lowchen",
  },
  {
    code: "maltese",
    latitude: 0.0,
    longitude: 0.0,
    name: "Maltese",
  },
  {
    code: "manchester_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Manchester Terrier",
  },
  {
    code: "maremma_sheepdog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Maremma Sheepdog",
  },
  {
    code: "mastiff",
    latitude: 0.0,
    longitude: 0.0,
    name: "Mastiff",
  },
  {
    code: "miniature_pinscher",
    latitude: 0.0,
    longitude: 0.0,
    name: "Miniature Pinscher",
  },
  {
    code: "neapolitan_mastiff",
    latitude: 0.0,
    longitude: 0.0,
    name: "Neapolitan Mastiff",
  },
  {
    code: "newfoundland",
    latitude: 0.0,
    longitude: 0.0,
    name: "Newfoundland",
  },
  {
    code: "norfolk_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Norfolk Terrier",
  },
  {
    code: "norwegian_buhund",
    latitude: 0.0,
    longitude: 0.0,
    name: "Norwegian Buhund",
  },
  {
    code: "norwegian_elkhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Norwegian Elkhound",
  },
  {
    code: "norwich_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Norwich Terrier",
  },
  {
    code: "nova_scotia_duck_tolling_retriever",
    latitude: 0.0,
    longitude: 0.0,
    name: "Nova Scotia Duck Tolling Retriever",
  },
  {
    code: "old_english_sheepdog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Old English Sheepdog",
  },
  {
    code: "otterhound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Otterhound",
  },
  {
    code: "papillon",
    latitude: 0.0,
    longitude: 0.0,
    name: "Papillon",
    variants: [
      {
        key: "phalene",
        label: "Phal\u00e8ne",
      },
    ],
  },
  {
    code: "parson_russell_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Parson Russell Terrier",
  },
  {
    code: "pekingese",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pekingese",
  },
  {
    code: "peruvian_hairless_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Peruvian Hairless Dog",
    variants: [
      {
        key: "large",
        label: "Large",
      },
      {
        key: "medium",
        label: "Medium",
      },
      {
        key: "small",
        label: "Small",
      },
    ],
  },
  {
    code: "petit_basset_griffon_vendeen",
    latitude: 0.0,
    longitude: 0.0,
    name: "Petit Basset Griffon Vendeen",
  },
  {
    code: "pharaoh_hound",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pharaoh Hound",
  },
  {
    code: "pointer",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pointer",
  },
  {
    code: "polish_lowland_sheepdog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Polish Lowland Sheepdog",
  },
  {
    code: "pomeranian",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pomeranian",
  },
  {
    code: "poodle",
    latitude: 0.0,
    longitude: 0.0,
    name: "Poodle",
    variants: [
      {
        key: "miniature",
        label: "Miniature",
      },
      {
        key: "standard",
        label: "Standard",
      },
      {
        key: "toy",
        label: "Toy",
      },
    ],
  },
  {
    code: "portuguese_podengo",
    latitude: 0.0,
    longitude: 0.0,
    name: "Portuguese Podengo",
    variants: [
      {
        key: "large_smooth_haired",
        label: "Large Smooth Haired",
      },
      {
        key: "large_wire_haired",
        label: "Large Wire Haired",
      },
      {
        key: "medium_smooth_haired",
        label: "Medium Smooth Haired",
      },
      {
        key: "medium_wire_haired",
        label: "Medium Wire Haired",
      },
      {
        key: "small_smooth_haired",
        label: "Small Smooth Haired",
      },
      {
        key: "small_wire_haired",
        label: "Small Wire Haired",
      },
    ],
  },
  {
    code: "portuguese_water_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Portuguese Water Dog",
  },
  {
    code: "pug",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pug",
  },
  {
    code: "puli",
    latitude: 0.0,
    longitude: 0.0,
    name: "Puli",
  },
  {
    code: "pumi",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pumi",
  },
  {
    code: "pyrenean_mastiff",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pyrenean Mastiff",
  },
  {
    code: "pyrenean_mountain_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pyrenean Mountain Dog",
  },
  {
    code: "pyrenean_sheepdog_longhaired",
    latitude: 0.0,
    longitude: 0.0,
    name: "Pyrenean Sheepdog Longhaired",
  },
  {
    code: "rhodesian_ridgeback",
    latitude: 0.0,
    longitude: 0.0,
    name: "Rhodesian Ridgeback",
  },
  {
    code: "rottweiler",
    latitude: 0.0,
    longitude: 0.0,
    name: "Rottweiler",
  },
  {
    code: "russian_black_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Russian Black Terrier",
  },
  {
    code: "russian_toy",
    latitude: 0.0,
    longitude: 0.0,
    name: "Russian Toy",
    variants: [
      {
        key: "long_haired",
        label: "Long Haired",
      },
      {
        key: "smooth_haired",
        label: "Smooth Haired",
      },
    ],
  },
  {
    code: "saluki",
    latitude: 0.0,
    longitude: 0.0,
    name: "Saluki",
  },
  {
    code: "samoyed",
    latitude: 0.0,
    longitude: 0.0,
    name: "Samoyed",
  },
  {
    code: "schipperke",
    latitude: 0.0,
    longitude: 0.0,
    name: "Schipperke",
  },
  {
    code: "schnauzer",
    latitude: 0.0,
    longitude: 0.0,
    name: "Schnauzer",
    variants: [
      {
        key: "giant",
        label: "Giant",
      },
      {
        key: "miniature",
        label: "Miniature",
      },
    ],
  },
  {
    code: "scottish_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Scottish Terrier",
  },
  {
    code: "sealyham_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Sealyham Terrier",
  },
  {
    code: "shar_pei",
    latitude: 0.0,
    longitude: 0.0,
    name: "Shar Pei",
  },
  {
    code: "shetland_sheepdog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Shetland Sheepdog",
  },
  {
    code: "shiba_inu",
    latitude: 0.0,
    longitude: 0.0,
    name: "Shiba Inu",
  },
  {
    code: "shih_tzu",
    latitude: 0.0,
    longitude: 0.0,
    name: "Shih Tzu",
  },
  {
    code: "siberian_husky",
    latitude: 0.0,
    longitude: 0.0,
    name: "Siberian Husky",
  },
  {
    code: "skye_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Skye Terrier",
  },
  {
    code: "sloughi",
    latitude: 0.0,
    longitude: 0.0,
    name: "Sloughi",
  },
  {
    code: "soft_coated_wheaten_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Soft Coated Wheaten Terrier",
  },
  {
    code: "spanish_mastiff",
    latitude: 0.0,
    longitude: 0.0,
    name: "Spanish Mastiff",
  },
  {
    code: "spanish_water_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Spanish Water Dog",
  },
  {
    code: "st_bernard",
    latitude: 0.0,
    longitude: 0.0,
    name: "St Bernard",
  },
  {
    code: "staffordshire_bull_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Staffordshire Bull Terrier",
  },
  {
    code: "sussex_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Sussex Spaniel",
  },
  {
    code: "swedish_lapphund",
    latitude: 0.0,
    longitude: 0.0,
    name: "Swedish Lapphund",
  },
  {
    code: "swedish_vallhund",
    latitude: 0.0,
    longitude: 0.0,
    name: "Swedish Vallhund",
  },
  {
    code: "tatra_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "Tatra Shepherd Dog",
  },
  {
    code: "tenterfield_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Tenterfield Terrier",
  },
  {
    code: "tibetan_mastiff",
    latitude: 0.0,
    longitude: 0.0,
    name: "Tibetan Mastiff",
  },
  {
    code: "tibetan_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Tibetan Spaniel",
  },
  {
    code: "tibetan_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Tibetan Terrier",
  },
  {
    code: "tornjak",
    latitude: 0.0,
    longitude: 0.0,
    name: "Tornjak",
  },
  {
    code: "weimaraner",
    latitude: 0.0,
    longitude: 0.0,
    name: "Weimaraner",
    variants: [
      {
        key: "long-haired",
        label: "Long-haired",
      },
    ],
  },
  {
    code: "welsh_corgi",
    latitude: 0.0,
    longitude: 0.0,
    name: "Welsh Corgi",
    variants: [
      {
        key: "cardigan",
        label: "Cardigan",
      },
      {
        key: "pembroke",
        label: "Pembroke",
      },
    ],
  },
  {
    code: "welsh_springer_spaniel",
    latitude: 0.0,
    longitude: 0.0,
    name: "Welsh Springer Spaniel",
  },
  {
    code: "welsh_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Welsh Terrier",
  },
  {
    code: "west_highland_white_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "West Highland White Terrier",
  },
  {
    code: "whippet",
    latitude: 0.0,
    longitude: 0.0,
    name: "Whippet",
  },
  {
    code: "white_swiss_shepherd_dog",
    latitude: 0.0,
    longitude: 0.0,
    name: "White Swiss Shepherd Dog",
  },
  {
    code: "wirehaired_slovakian_pointer",
    latitude: 0.0,
    longitude: 0.0,
    name: "Wirehaired Slovakian Pointer",
  },
  {
    code: "xoloitzcuintle",
    latitude: 0.0,
    longitude: 0.0,
    name: "Xoloitzcuintle",
    variants: [
      {
        key: "intermediate",
        label: "Intermediate",
      },
      {
        key: "miniature",
        label: "Miniature",
      },
      {
        key: "standard",
        label: "Standard",
      },
    ],
  },
  {
    code: "yakutian_laika",
    latitude: 0.0,
    longitude: 0.0,
    name: "Yakutian Laika",
  },
  {
    code: "yorkshire_terrier",
    latitude: 0.0,
    longitude: 0.0,
    name: "Yorkshire Terrier",
  },
] as const;

export type BreedCode = typeof breeds[number]["code"];
