export const originNames: Record<string, string> = {
  afghanistan: "Afghanistan",
  argentina: "Argentina",
  australia: "Australia",
  austria: "Austria",
  belgium: "Belgium",
  bolivia: "Bolivia",
  bosnia_and_herzegovina: "Bosnia and Herzegovina",
  brazil: "Brazil",
  bulgaria: "Bulgaria",
  canada: "Canada",
  chile: "Chile",
  china: "China",
  colombia: "Colombia",
  croatia: "Croatia",
  cuba: "Cuba",
  czech_republic: "Czech Republic",
  drc: "Democratic Republic of the Congo",
  denmark: "Denmark",
  ecuador: "Ecuador",
  estonia: "Estonia",
  finland: "Finland",
  france: "France",
  georgia: "Georgia",
  germany: "Germany",
  greece: "Greece",
  greenland: "Greenland",
  guatemala: "Guatemala",
  hungary: "Hungary",
  iceland: "Iceland",
  india: "India",
  indonesia: "Indonesia",
  ireland: "Ireland",
  italy: "Italy",
  japan: "Japan",
  korea: "Korea",
  lithuania: "Lithuania",
  madagascar: "Madagascar",
  malaysia: "Malaysia",
  malta: "Malta",
  mexico: "Mexico",
  middle_east: "Middle East",
  montenegro: "Montenegro",
  netherlands: "Netherlands",
  new_zealand: "New Zealand",
  north_macedonia: "North Macedonia",
  norway: "Norway",
  pakistan: "Pakistan",
  png: "Papua New Guinea",
  peru: "Peru",
  philippines: "Philippines",
  poland: "Poland",
  portugal: "Portugal",
  prussia: "Prussia",
  romania: "Romania",
  russia: "Russia",
  serbia: "Serbia",
  slovakia: "Slovakia",
  slovenia: "Slovenia",
  south_africa: "South Africa",
  soviet_union: "Soviet Union",
  spain: "Spain",
  sweden: "Sweden",
  switzerland: "Switzerland",
  thailand: "Thailand",
  tibet: "Tibet",
  turkey: "Turkey",
  ukraine: "Ukraine",
  uk: "United Kingdom",
  usa: "United States of America",
  uruguay: "Urguguay",
};
